import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createProjectionFit, createReferenceGeometry, findingsFromProjectionFit, comparisonMetricsFromProjectionFit, routeFinding} from '../skills/refas/scripts/lib/index.mjs';
const D=c=>c.repeat(64);
function ref(){return createReferenceGeometry({scopeId:'whole',sourceSha256:D('a'),anchors:[
{id:'aa',importance:'macro',evidenceRefs:['source.png'],xy:[.2,.2],visibility:'visible',confidence:1},{id:'bb',importance:'macro',evidenceRefs:['source.png'],xy:[.4,.4],visibility:'visible',confidence:1},{id:'cc',importance:'macro',evidenceRefs:['source.png'],xy:[.7,.5],visibility:'visible',confidence:1}],chains:[{id:'abc-chain',importance:'macro',evidenceRefs:['source.png'],anchorIds:['aa','bb','cc']}],axes:[{id:'ab-axis',importance:'macro',evidenceRefs:['source.png'],fromAnchorId:'aa',toAnchorId:'bb'}],negativeSpaces:[{id:'gap',importance:'macro',evidenceRefs:['source.png'],polygon:[[.2,.3],[.3,.5],[.5,.35]]}],attestation:{attested:true,evidenceRefs:['source.png']}})}
const p=(referenceId,projectedXY)=>({referenceId,projectedXY,binding:{kind:'node-local-point',nodeId:`node-${referenceId}`,localPoint:[0,0,0]}});
test('material projection disagreement becomes routed typed findings',()=>{const g=ref();const fit=createProjectionFit({referenceGeometry:g,cameraHypothesisId:'cam-a',cameraDigest:D('b'),modelBindingDigest:D('c'),anchorProjections:[p('aa',[.45,.15]),p('bb',[.60,.22]),p('cc',[.58,.72])],negativeSpaceProjections:[{referenceId:'gap',polygon:[[.6,.6],[.7,.8],[.9,.7]]}],evidenceRefs:['render.png']});const findings=findingsFromProjectionFit(fit);assert.ok(findings.some(x=>x.category==='orientation-mismatch'&&x.ownerCapability==='spatial-hypotheses'));assert.ok(findings.some(x=>x.category==='mass-proportion-mismatch'&&x.ownerCapability==='shape-reconstruction'));assert.ok(findings.some(x=>x.category==='silhouette-mismatch'&&x.ownerCapability==='shape-reconstruction'));for(const finding of findings){assert.equal(finding.blocking,true);assert.ok(finding.evidenceRefs.length>0);assert.equal(routeFinding({finding}).action,'REOPEN_CAPABILITY');}const metrics=comparisonMetricsFromProjectionFit(fit);assert.equal(metrics.projectionFitDigest,fit.projectionFitDigest);assert.equal(metrics.landmarkResidualRmse,fit.metrics.macroAnchorRmseNormalized);});
test('good fit produces no blocking finding',()=>{const g=ref();const fit=createProjectionFit({referenceGeometry:g,cameraHypothesisId:'cam-a',cameraDigest:D('b'),modelBindingDigest:D('c'),anchorProjections:[p('aa',[.201,.201]),p('bb',[.401,.401]),p('cc',[.701,.501])],negativeSpaceProjections:[{referenceId:'gap',polygon:[[.2,.3],[.3,.5],[.5,.35]]}]});assert.deepEqual(findingsFromProjectionFit(fit),[]);});
